// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
	API: {
		GraphQL: {
			endpoint:
				"https://4lm4oskh7zffphvxtq5yid7lyy.appsync-api.us-east-2.amazonaws.com/graphql",
			region: "us-east-2",
			defaultAuthMode: "userPool",
		},
	},
}

export default config
